<?php // this is an autogenerated file - do not edit (created Sat, 25 Dec 2010 17:20:25 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'theseer\\directoryscanner\\directoryscanner' => '/src/directoryscanner.php',
            'theseer\\directoryscanner\\directoryscannerexception' => '/src/directoryscanner.php',
            'theseer\\directoryscanner\\filesonlyfilteriterator' => '/src/filesonlyfilter.php',
            'theseer\\directoryscanner\\includeexcludefilteriterator' => '/src/includeexcludefilter.php',
            'theseer\\directoryscanner\\phpfilteriterator' => '/src/phpfilter.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
